//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskNgTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskrecord
    {
        public int RecordID { get; set; }
        public string TaskName { get; set; }
        public string Description { get; set; }
        public int UserID { get; set; }
        public string Duration { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string enterdDuration { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public int TaskID { get; set; }
    
        public virtual position position { get; set; }
        public virtual role role { get; set; }
        public virtual task task { get; set; }
    }
}
