//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskNgTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ptg_Task_TrackerEntities : DbContext
    {
        public Ptg_Task_TrackerEntities()
            : base("name=Ptg_Task_TrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<taskrecord> taskrecords { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
